import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';

import '@mantine/core/styles.css';
import './globals.css';

import { HomeLayout } from '@/components/layouts';

import { theme } from '@/theme';

const nonito = Nunito({
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  display: 'swap',
  style: ['normal', 'italic'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <head>
        <ColorSchemeScript defaultColorScheme='light' />
      </head>
      <body className={nonito.className}>
        <NextIntlClientProvider messages={messages}>
          <MantineProvider theme={theme}>
            <HomeLayout>{children}</HomeLayout>
          </MantineProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
